// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.service2;

public interface authenticationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authentication)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string authentication = 1;</code>
   */
  java.lang.String getAuthentication();
  /**
   * <code>string authentication = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthenticationBytes();
}
