// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package grpc.service2;

public interface credentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string password = 1;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 1;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
