// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service3;

public interface balanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:balanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string balance = 1;</code>
   */
  java.lang.String getBalance();
  /**
   * <code>string balance = 1;</code>
   */
  com.google.protobuf.ByteString
      getBalanceBytes();
}
