// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service3;

public final class NewServiceImpl {
  private NewServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_balanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_balanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_balanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_balanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transactionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transactionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_transactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\"!\n\016balanceRequest\022\017\n\007re" +
      "quest\030\001 \001(\t\"\"\n\017balanceResponse\022\017\n\007balanc" +
      "e\030\001 \001(\t\"A\n\022transactionRequest\022\021\n\taccount" +
      "ID\030\001 \001(\005\022\030\n\020transactionTitle\030\002 \001(\t\"?\n\023tr" +
      "ansactionResponse\022\r\n\005title\030\001 \001(\t\022\031\n\021tran" +
      "sactionStatus\030\002 \001(\t2}\n\nnewService\0220\n\013vie" +
      "wBalance\022\017.balanceRequest\032\020.balanceRespo" +
      "nse\022=\n\020viewTransactions\022\023.transactionReq" +
      "uest\032\024.transactionResponseB!\n\rgrpc.servi" +
      "ce3B\016NewServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_balanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_balanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_balanceRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_balanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_balanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_balanceResponse_descriptor,
        new java.lang.String[] { "Balance", });
    internal_static_transactionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_transactionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transactionRequest_descriptor,
        new java.lang.String[] { "AccountID", "TransactionTitle", });
    internal_static_transactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_transactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_transactionResponse_descriptor,
        new java.lang.String[] { "Title", "TransactionStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
