// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service3;

public interface transactionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transactionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 accountID = 1;</code>
   */
  int getAccountID();

  /**
   * <code>string transactionTitle = 2;</code>
   */
  java.lang.String getTransactionTitle();
  /**
   * <code>string transactionTitle = 2;</code>
   */
  com.google.protobuf.ByteString
      getTransactionTitleBytes();
}
