// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package grpc.service3;

public interface transactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string transactionStatus = 2;</code>
   */
  java.lang.String getTransactionStatus();
  /**
   * <code>string transactionStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getTransactionStatusBytes();
}
