// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package grpc.service4;

public interface alertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alerts = 1;</code>
   */
  java.lang.String getAlerts();
  /**
   * <code>string alerts = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertsBytes();
}
