// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package grpc.service4;

public final class NewServiceImpl {
  private NewServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_alertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_alertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service4.proto\"\037\n\014alertRequest\022\017\n\007requ" +
      "est\030\001 \001(\t\"\037\n\ralertResponse\022\016\n\006alerts\030\001 \001" +
      "(\t2>\n\nnewService\0220\n\raccountAlerts\022\r.aler" +
      "tRequest\032\016.alertResponse0\001B!\n\rgrpc.servi" +
      "ce4B\016NewServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_alertRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_alertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alertRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_alertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_alertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_alertResponse_descriptor,
        new java.lang.String[] { "Alerts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
