// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.service1;

public interface cancelPaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cancelPayment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cancel = 1;</code>
   */
  java.lang.String getCancel();
  /**
   * <code>string cancel = 1;</code>
   */
  com.google.protobuf.ByteString
      getCancelBytes();
}
