// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.service1;

public interface cancelledOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cancelled)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cancelled = 1;</code>
   */
  java.lang.String getCancelled();
  /**
   * <code>string cancelled = 1;</code>
   */
  com.google.protobuf.ByteString
      getCancelledBytes();
}
