// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.service1;

public final class NewServiceImpl {
  private NewServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_paymentDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_paymentDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_confirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_confirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cancelPayment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cancelPayment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cancelled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cancelled_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\"?\n\016paymentDetails\022\014\n\004na" +
      "me\030\001 \001(\t\022\017\n\007account\030\002 \001(\t\022\016\n\006amount\030\003 \001(" +
      "\001\"$\n\014confirmation\022\024\n\014confirmation\030\001 \001(\t\"" +
      "\037\n\rcancelPayment\022\016\n\006cancel\030\001 \001(\t\"\036\n\tcanc" +
      "elled\022\021\n\tcancelled\030\001 \001(\t2D\n\nnewService\0226" +
      "\n\026CancelRecurringPayment\022\016.cancelPayment" +
      "\032\n.cancelled\"\000B!\n\rgrpc.service1B\016NewServ" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_paymentDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_paymentDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_paymentDetails_descriptor,
        new java.lang.String[] { "Name", "Account", "Amount", });
    internal_static_confirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_confirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_confirmation_descriptor,
        new java.lang.String[] { "Confirmation", });
    internal_static_cancelPayment_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cancelPayment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cancelPayment_descriptor,
        new java.lang.String[] { "Cancel", });
    internal_static_cancelled_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cancelled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cancelled_descriptor,
        new java.lang.String[] { "Cancelled", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
