// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package grpc.service1;

public interface paymentDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:paymentDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string account = 2;</code>
   */
  java.lang.String getAccount();
  /**
   * <code>string account = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccountBytes();

  /**
   * <code>double amount = 3;</code>
   */
  double getAmount();
}
